// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package aviatrix

import (
	"context"
	"reflect"

	"github.com/pkg/errors"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type Account struct {
	pulumi.CustomResourceState

	// Account name. This can be used for logging in to CloudN console or UserConnect controller.
	AccountName pulumi.StringOutput `pulumi:"accountName"`
	// Alibaba Cloud Access Key.
	AlicloudAccessKey pulumi.StringPtrOutput `pulumi:"alicloudAccessKey"`
	// Alibaba Cloud Account ID to associate with Aviatrix account.
	AlicloudAccountId pulumi.StringPtrOutput `pulumi:"alicloudAccountId"`
	// Alibaba Cloud Secret Key.
	AlicloudSecretKey pulumi.StringPtrOutput `pulumi:"alicloudSecretKey"`
	// Azure Application ID.
	ArmApplicationId pulumi.StringPtrOutput `pulumi:"armApplicationId"`
	// Azure Application Key.
	ArmApplicationKey pulumi.StringPtrOutput `pulumi:"armApplicationKey"`
	// Azure Directory ID.
	ArmDirectoryId pulumi.StringPtrOutput `pulumi:"armDirectoryId"`
	// Azure Subscription ID.
	ArmSubscriptionId pulumi.StringPtrOutput `pulumi:"armSubscriptionId"`
	// Enable account audit.
	AuditAccount pulumi.BoolPtrOutput `pulumi:"auditAccount"`
	// AWS Access Key.
	AwsAccessKey pulumi.StringPtrOutput `pulumi:"awsAccessKey"`
	// AWS Account number to associate with Aviatrix account. Should be 12 digits.
	AwsAccountNumber pulumi.StringPtrOutput `pulumi:"awsAccountNumber"`
	// AWS Top Secret Region or Secret Region Custom Certificate Authority file path on the controller.
	AwsCaCertPath pulumi.StringOutput `pulumi:"awsCaCertPath"`
	// AWS App role ARN for gateways.
	AwsGatewayRoleApp pulumi.StringPtrOutput `pulumi:"awsGatewayRoleApp"`
	// AWS EC2 role ARN for gateways.
	AwsGatewayRoleEc2 pulumi.StringPtrOutput `pulumi:"awsGatewayRoleEc2"`
	// AWS IAM-role based flag.
	AwsIam pulumi.BoolPtrOutput `pulumi:"awsIam"`
	// AWS App role ARN.
	AwsRoleApp pulumi.StringOutput `pulumi:"awsRoleApp"`
	// AWS EC2 role ARN.
	AwsRoleEc2 pulumi.StringOutput `pulumi:"awsRoleEc2"`
	// AWS Secret Key.
	AwsSecretKey pulumi.StringPtrOutput `pulumi:"awsSecretKey"`
	// AWS China Access Key.
	AwschinaAccessKey pulumi.StringPtrOutput `pulumi:"awschinaAccessKey"`
	// AWS China Account Number.
	AwschinaAccountNumber pulumi.StringPtrOutput `pulumi:"awschinaAccountNumber"`
	// AWS China IAM-role based flag.
	AwschinaIam pulumi.BoolPtrOutput `pulumi:"awschinaIam"`
	// AWS China App Role ARN.
	AwschinaRoleApp pulumi.StringOutput `pulumi:"awschinaRoleApp"`
	// AWS China EC2 Role ARN.
	AwschinaRoleEc2 pulumi.StringOutput `pulumi:"awschinaRoleEc2"`
	// AWS China Secret Key.
	AwschinaSecretKey pulumi.StringPtrOutput `pulumi:"awschinaSecretKey"`
	// AWS Gov Access Key.
	AwsgovAccessKey pulumi.StringPtrOutput `pulumi:"awsgovAccessKey"`
	// AWS Gov Account number to associate with Aviatrix account.
	AwsgovAccountNumber pulumi.StringPtrOutput `pulumi:"awsgovAccountNumber"`
	// AWSGov IAM-role based flag
	AwsgovIam pulumi.BoolPtrOutput `pulumi:"awsgovIam"`
	// AWSGov App role ARN
	AwsgovRoleApp pulumi.StringOutput `pulumi:"awsgovRoleApp"`
	// AWSGov EC2 role ARN
	AwsgovRoleEc2 pulumi.StringOutput `pulumi:"awsgovRoleEc2"`
	// AWS Gov Secret Key.
	AwsgovSecretKey pulumi.StringPtrOutput `pulumi:"awsgovSecretKey"`
	// AWS Secret Region Account Number.
	AwssAccountNumber pulumi.StringPtrOutput `pulumi:"awssAccountNumber"`
	// AWS Secret Region Custom Certificate Authority file path.
	AwssCaChainCert pulumi.StringPtrOutput `pulumi:"awssCaChainCert"`
	// AWS Secret Region CAP Account Name.
	AwssCapAccountName pulumi.StringPtrOutput `pulumi:"awssCapAccountName"`
	// AWS Secret Region CAP Agency.
	AwssCapAgency pulumi.StringPtrOutput `pulumi:"awssCapAgency"`
	// AWS Secret Region CAP Certificate file path.
	AwssCapCert pulumi.StringPtrOutput `pulumi:"awssCapCert"`
	// AWS Secret Region CAP Certificate Key file path.
	AwssCapCertKey pulumi.StringPtrOutput `pulumi:"awssCapCertKey"`
	// AWS Secret Region CAP Certificate Key file path on the controller.
	AwssCapCertKeyPath pulumi.StringOutput `pulumi:"awssCapCertKeyPath"`
	// AWS Secret Region CAP Certificate file path on the controller.
	AwssCapCertPath pulumi.StringOutput `pulumi:"awssCapCertPath"`
	// AWS Secret Region CAP Role Name.
	AwssCapRoleName pulumi.StringPtrOutput `pulumi:"awssCapRoleName"`
	// AWS Secret Region CAP Endpoint URL.
	AwssCapUrl pulumi.StringPtrOutput `pulumi:"awssCapUrl"`
	// AWS Top Secret Region Account Number.
	AwstsAccountNumber pulumi.StringPtrOutput `pulumi:"awstsAccountNumber"`
	// AWS Top Secret Region Custom Certificate Authority file path.
	AwstsCaChainCert pulumi.StringPtrOutput `pulumi:"awstsCaChainCert"`
	// AWS Top Secret Region CAP Agency.
	AwstsCapAgency pulumi.StringPtrOutput `pulumi:"awstsCapAgency"`
	// AWS Top Secret Region CAP Certificate file path.
	AwstsCapCert pulumi.StringPtrOutput `pulumi:"awstsCapCert"`
	// AWS Top Secret Region CAP Certificate Key file path.
	AwstsCapCertKey pulumi.StringPtrOutput `pulumi:"awstsCapCertKey"`
	// AWS Top Secret Region CAP Certificate Key file path on the controller.
	AwstsCapCertKeyPath pulumi.StringOutput `pulumi:"awstsCapCertKeyPath"`
	// AWS Top Secret Region CAP Certificate file path on the controller.
	AwstsCapCertPath pulumi.StringOutput `pulumi:"awstsCapCertPath"`
	// AWS Top Secret Region CAP Mission.
	AwstsCapMission pulumi.StringPtrOutput `pulumi:"awstsCapMission"`
	// AWS Top Secret Region CAP Role Name.
	AwstsCapRoleName pulumi.StringPtrOutput `pulumi:"awstsCapRoleName"`
	// AWS Top Secret Region CAP Endpoint URL.
	AwstsCapUrl pulumi.StringPtrOutput `pulumi:"awstsCapUrl"`
	// Azure China Application ID.
	AzurechinaApplicationId pulumi.StringPtrOutput `pulumi:"azurechinaApplicationId"`
	// Azure China Application Key.
	AzurechinaApplicationKey pulumi.StringPtrOutput `pulumi:"azurechinaApplicationKey"`
	// Azure China Directory ID.
	AzurechinaDirectoryId pulumi.StringPtrOutput `pulumi:"azurechinaDirectoryId"`
	// Azure China Subscription ID.
	AzurechinaSubscriptionId pulumi.StringPtrOutput `pulumi:"azurechinaSubscriptionId"`
	// Azure Gov Application ID.
	AzuregovApplicationId pulumi.StringPtrOutput `pulumi:"azuregovApplicationId"`
	// Azure Gov Application Key.
	AzuregovApplicationKey pulumi.StringPtrOutput `pulumi:"azuregovApplicationKey"`
	// Azure Gov Directory ID.
	AzuregovDirectoryId pulumi.StringPtrOutput `pulumi:"azuregovDirectoryId"`
	// Azure Gov Subscription ID.
	AzuregovSubscriptionId pulumi.StringPtrOutput `pulumi:"azuregovSubscriptionId"`
	// Type of cloud service provider.
	CloudType pulumi.IntOutput `pulumi:"cloudType"`
	// GCloud Project credentials local file path.
	GcloudProjectCredentialsFilepath pulumi.StringPtrOutput `pulumi:"gcloudProjectCredentialsFilepath"`
	// GCloud Project ID.
	GcloudProjectId pulumi.StringPtrOutput `pulumi:"gcloudProjectId"`
	// OCI API Private Key local file path.
	OciApiPrivateKeyFilepath pulumi.StringPtrOutput `pulumi:"ociApiPrivateKeyFilepath"`
	// OCI Compartment OCID.
	OciCompartmentId pulumi.StringPtrOutput `pulumi:"ociCompartmentId"`
	// OCI Tenancy OCID.
	OciTenancyId pulumi.StringPtrOutput `pulumi:"ociTenancyId"`
	// OCI User OCID.
	OciUserId pulumi.StringPtrOutput `pulumi:"ociUserId"`
}

// NewAccount registers a new resource with the given unique name, arguments, and options.
func NewAccount(ctx *pulumi.Context,
	name string, args *AccountArgs, opts ...pulumi.ResourceOption) (*Account, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.AccountName == nil {
		return nil, errors.New("invalid value for required argument 'AccountName'")
	}
	if args.CloudType == nil {
		return nil, errors.New("invalid value for required argument 'CloudType'")
	}
	var resource Account
	err := ctx.RegisterResource("aviatrix:index/account:Account", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetAccount gets an existing Account resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetAccount(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *AccountState, opts ...pulumi.ResourceOption) (*Account, error) {
	var resource Account
	err := ctx.ReadResource("aviatrix:index/account:Account", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering Account resources.
type accountState struct {
	// Account name. This can be used for logging in to CloudN console or UserConnect controller.
	AccountName *string `pulumi:"accountName"`
	// Alibaba Cloud Access Key.
	AlicloudAccessKey *string `pulumi:"alicloudAccessKey"`
	// Alibaba Cloud Account ID to associate with Aviatrix account.
	AlicloudAccountId *string `pulumi:"alicloudAccountId"`
	// Alibaba Cloud Secret Key.
	AlicloudSecretKey *string `pulumi:"alicloudSecretKey"`
	// Azure Application ID.
	ArmApplicationId *string `pulumi:"armApplicationId"`
	// Azure Application Key.
	ArmApplicationKey *string `pulumi:"armApplicationKey"`
	// Azure Directory ID.
	ArmDirectoryId *string `pulumi:"armDirectoryId"`
	// Azure Subscription ID.
	ArmSubscriptionId *string `pulumi:"armSubscriptionId"`
	// Enable account audit.
	AuditAccount *bool `pulumi:"auditAccount"`
	// AWS Access Key.
	AwsAccessKey *string `pulumi:"awsAccessKey"`
	// AWS Account number to associate with Aviatrix account. Should be 12 digits.
	AwsAccountNumber *string `pulumi:"awsAccountNumber"`
	// AWS Top Secret Region or Secret Region Custom Certificate Authority file path on the controller.
	AwsCaCertPath *string `pulumi:"awsCaCertPath"`
	// AWS App role ARN for gateways.
	AwsGatewayRoleApp *string `pulumi:"awsGatewayRoleApp"`
	// AWS EC2 role ARN for gateways.
	AwsGatewayRoleEc2 *string `pulumi:"awsGatewayRoleEc2"`
	// AWS IAM-role based flag.
	AwsIam *bool `pulumi:"awsIam"`
	// AWS App role ARN.
	AwsRoleApp *string `pulumi:"awsRoleApp"`
	// AWS EC2 role ARN.
	AwsRoleEc2 *string `pulumi:"awsRoleEc2"`
	// AWS Secret Key.
	AwsSecretKey *string `pulumi:"awsSecretKey"`
	// AWS China Access Key.
	AwschinaAccessKey *string `pulumi:"awschinaAccessKey"`
	// AWS China Account Number.
	AwschinaAccountNumber *string `pulumi:"awschinaAccountNumber"`
	// AWS China IAM-role based flag.
	AwschinaIam *bool `pulumi:"awschinaIam"`
	// AWS China App Role ARN.
	AwschinaRoleApp *string `pulumi:"awschinaRoleApp"`
	// AWS China EC2 Role ARN.
	AwschinaRoleEc2 *string `pulumi:"awschinaRoleEc2"`
	// AWS China Secret Key.
	AwschinaSecretKey *string `pulumi:"awschinaSecretKey"`
	// AWS Gov Access Key.
	AwsgovAccessKey *string `pulumi:"awsgovAccessKey"`
	// AWS Gov Account number to associate with Aviatrix account.
	AwsgovAccountNumber *string `pulumi:"awsgovAccountNumber"`
	// AWSGov IAM-role based flag
	AwsgovIam *bool `pulumi:"awsgovIam"`
	// AWSGov App role ARN
	AwsgovRoleApp *string `pulumi:"awsgovRoleApp"`
	// AWSGov EC2 role ARN
	AwsgovRoleEc2 *string `pulumi:"awsgovRoleEc2"`
	// AWS Gov Secret Key.
	AwsgovSecretKey *string `pulumi:"awsgovSecretKey"`
	// AWS Secret Region Account Number.
	AwssAccountNumber *string `pulumi:"awssAccountNumber"`
	// AWS Secret Region Custom Certificate Authority file path.
	AwssCaChainCert *string `pulumi:"awssCaChainCert"`
	// AWS Secret Region CAP Account Name.
	AwssCapAccountName *string `pulumi:"awssCapAccountName"`
	// AWS Secret Region CAP Agency.
	AwssCapAgency *string `pulumi:"awssCapAgency"`
	// AWS Secret Region CAP Certificate file path.
	AwssCapCert *string `pulumi:"awssCapCert"`
	// AWS Secret Region CAP Certificate Key file path.
	AwssCapCertKey *string `pulumi:"awssCapCertKey"`
	// AWS Secret Region CAP Certificate Key file path on the controller.
	AwssCapCertKeyPath *string `pulumi:"awssCapCertKeyPath"`
	// AWS Secret Region CAP Certificate file path on the controller.
	AwssCapCertPath *string `pulumi:"awssCapCertPath"`
	// AWS Secret Region CAP Role Name.
	AwssCapRoleName *string `pulumi:"awssCapRoleName"`
	// AWS Secret Region CAP Endpoint URL.
	AwssCapUrl *string `pulumi:"awssCapUrl"`
	// AWS Top Secret Region Account Number.
	AwstsAccountNumber *string `pulumi:"awstsAccountNumber"`
	// AWS Top Secret Region Custom Certificate Authority file path.
	AwstsCaChainCert *string `pulumi:"awstsCaChainCert"`
	// AWS Top Secret Region CAP Agency.
	AwstsCapAgency *string `pulumi:"awstsCapAgency"`
	// AWS Top Secret Region CAP Certificate file path.
	AwstsCapCert *string `pulumi:"awstsCapCert"`
	// AWS Top Secret Region CAP Certificate Key file path.
	AwstsCapCertKey *string `pulumi:"awstsCapCertKey"`
	// AWS Top Secret Region CAP Certificate Key file path on the controller.
	AwstsCapCertKeyPath *string `pulumi:"awstsCapCertKeyPath"`
	// AWS Top Secret Region CAP Certificate file path on the controller.
	AwstsCapCertPath *string `pulumi:"awstsCapCertPath"`
	// AWS Top Secret Region CAP Mission.
	AwstsCapMission *string `pulumi:"awstsCapMission"`
	// AWS Top Secret Region CAP Role Name.
	AwstsCapRoleName *string `pulumi:"awstsCapRoleName"`
	// AWS Top Secret Region CAP Endpoint URL.
	AwstsCapUrl *string `pulumi:"awstsCapUrl"`
	// Azure China Application ID.
	AzurechinaApplicationId *string `pulumi:"azurechinaApplicationId"`
	// Azure China Application Key.
	AzurechinaApplicationKey *string `pulumi:"azurechinaApplicationKey"`
	// Azure China Directory ID.
	AzurechinaDirectoryId *string `pulumi:"azurechinaDirectoryId"`
	// Azure China Subscription ID.
	AzurechinaSubscriptionId *string `pulumi:"azurechinaSubscriptionId"`
	// Azure Gov Application ID.
	AzuregovApplicationId *string `pulumi:"azuregovApplicationId"`
	// Azure Gov Application Key.
	AzuregovApplicationKey *string `pulumi:"azuregovApplicationKey"`
	// Azure Gov Directory ID.
	AzuregovDirectoryId *string `pulumi:"azuregovDirectoryId"`
	// Azure Gov Subscription ID.
	AzuregovSubscriptionId *string `pulumi:"azuregovSubscriptionId"`
	// Type of cloud service provider.
	CloudType *int `pulumi:"cloudType"`
	// GCloud Project credentials local file path.
	GcloudProjectCredentialsFilepath *string `pulumi:"gcloudProjectCredentialsFilepath"`
	// GCloud Project ID.
	GcloudProjectId *string `pulumi:"gcloudProjectId"`
	// OCI API Private Key local file path.
	OciApiPrivateKeyFilepath *string `pulumi:"ociApiPrivateKeyFilepath"`
	// OCI Compartment OCID.
	OciCompartmentId *string `pulumi:"ociCompartmentId"`
	// OCI Tenancy OCID.
	OciTenancyId *string `pulumi:"ociTenancyId"`
	// OCI User OCID.
	OciUserId *string `pulumi:"ociUserId"`
}

type AccountState struct {
	// Account name. This can be used for logging in to CloudN console or UserConnect controller.
	AccountName pulumi.StringPtrInput
	// Alibaba Cloud Access Key.
	AlicloudAccessKey pulumi.StringPtrInput
	// Alibaba Cloud Account ID to associate with Aviatrix account.
	AlicloudAccountId pulumi.StringPtrInput
	// Alibaba Cloud Secret Key.
	AlicloudSecretKey pulumi.StringPtrInput
	// Azure Application ID.
	ArmApplicationId pulumi.StringPtrInput
	// Azure Application Key.
	ArmApplicationKey pulumi.StringPtrInput
	// Azure Directory ID.
	ArmDirectoryId pulumi.StringPtrInput
	// Azure Subscription ID.
	ArmSubscriptionId pulumi.StringPtrInput
	// Enable account audit.
	AuditAccount pulumi.BoolPtrInput
	// AWS Access Key.
	AwsAccessKey pulumi.StringPtrInput
	// AWS Account number to associate with Aviatrix account. Should be 12 digits.
	AwsAccountNumber pulumi.StringPtrInput
	// AWS Top Secret Region or Secret Region Custom Certificate Authority file path on the controller.
	AwsCaCertPath pulumi.StringPtrInput
	// AWS App role ARN for gateways.
	AwsGatewayRoleApp pulumi.StringPtrInput
	// AWS EC2 role ARN for gateways.
	AwsGatewayRoleEc2 pulumi.StringPtrInput
	// AWS IAM-role based flag.
	AwsIam pulumi.BoolPtrInput
	// AWS App role ARN.
	AwsRoleApp pulumi.StringPtrInput
	// AWS EC2 role ARN.
	AwsRoleEc2 pulumi.StringPtrInput
	// AWS Secret Key.
	AwsSecretKey pulumi.StringPtrInput
	// AWS China Access Key.
	AwschinaAccessKey pulumi.StringPtrInput
	// AWS China Account Number.
	AwschinaAccountNumber pulumi.StringPtrInput
	// AWS China IAM-role based flag.
	AwschinaIam pulumi.BoolPtrInput
	// AWS China App Role ARN.
	AwschinaRoleApp pulumi.StringPtrInput
	// AWS China EC2 Role ARN.
	AwschinaRoleEc2 pulumi.StringPtrInput
	// AWS China Secret Key.
	AwschinaSecretKey pulumi.StringPtrInput
	// AWS Gov Access Key.
	AwsgovAccessKey pulumi.StringPtrInput
	// AWS Gov Account number to associate with Aviatrix account.
	AwsgovAccountNumber pulumi.StringPtrInput
	// AWSGov IAM-role based flag
	AwsgovIam pulumi.BoolPtrInput
	// AWSGov App role ARN
	AwsgovRoleApp pulumi.StringPtrInput
	// AWSGov EC2 role ARN
	AwsgovRoleEc2 pulumi.StringPtrInput
	// AWS Gov Secret Key.
	AwsgovSecretKey pulumi.StringPtrInput
	// AWS Secret Region Account Number.
	AwssAccountNumber pulumi.StringPtrInput
	// AWS Secret Region Custom Certificate Authority file path.
	AwssCaChainCert pulumi.StringPtrInput
	// AWS Secret Region CAP Account Name.
	AwssCapAccountName pulumi.StringPtrInput
	// AWS Secret Region CAP Agency.
	AwssCapAgency pulumi.StringPtrInput
	// AWS Secret Region CAP Certificate file path.
	AwssCapCert pulumi.StringPtrInput
	// AWS Secret Region CAP Certificate Key file path.
	AwssCapCertKey pulumi.StringPtrInput
	// AWS Secret Region CAP Certificate Key file path on the controller.
	AwssCapCertKeyPath pulumi.StringPtrInput
	// AWS Secret Region CAP Certificate file path on the controller.
	AwssCapCertPath pulumi.StringPtrInput
	// AWS Secret Region CAP Role Name.
	AwssCapRoleName pulumi.StringPtrInput
	// AWS Secret Region CAP Endpoint URL.
	AwssCapUrl pulumi.StringPtrInput
	// AWS Top Secret Region Account Number.
	AwstsAccountNumber pulumi.StringPtrInput
	// AWS Top Secret Region Custom Certificate Authority file path.
	AwstsCaChainCert pulumi.StringPtrInput
	// AWS Top Secret Region CAP Agency.
	AwstsCapAgency pulumi.StringPtrInput
	// AWS Top Secret Region CAP Certificate file path.
	AwstsCapCert pulumi.StringPtrInput
	// AWS Top Secret Region CAP Certificate Key file path.
	AwstsCapCertKey pulumi.StringPtrInput
	// AWS Top Secret Region CAP Certificate Key file path on the controller.
	AwstsCapCertKeyPath pulumi.StringPtrInput
	// AWS Top Secret Region CAP Certificate file path on the controller.
	AwstsCapCertPath pulumi.StringPtrInput
	// AWS Top Secret Region CAP Mission.
	AwstsCapMission pulumi.StringPtrInput
	// AWS Top Secret Region CAP Role Name.
	AwstsCapRoleName pulumi.StringPtrInput
	// AWS Top Secret Region CAP Endpoint URL.
	AwstsCapUrl pulumi.StringPtrInput
	// Azure China Application ID.
	AzurechinaApplicationId pulumi.StringPtrInput
	// Azure China Application Key.
	AzurechinaApplicationKey pulumi.StringPtrInput
	// Azure China Directory ID.
	AzurechinaDirectoryId pulumi.StringPtrInput
	// Azure China Subscription ID.
	AzurechinaSubscriptionId pulumi.StringPtrInput
	// Azure Gov Application ID.
	AzuregovApplicationId pulumi.StringPtrInput
	// Azure Gov Application Key.
	AzuregovApplicationKey pulumi.StringPtrInput
	// Azure Gov Directory ID.
	AzuregovDirectoryId pulumi.StringPtrInput
	// Azure Gov Subscription ID.
	AzuregovSubscriptionId pulumi.StringPtrInput
	// Type of cloud service provider.
	CloudType pulumi.IntPtrInput
	// GCloud Project credentials local file path.
	GcloudProjectCredentialsFilepath pulumi.StringPtrInput
	// GCloud Project ID.
	GcloudProjectId pulumi.StringPtrInput
	// OCI API Private Key local file path.
	OciApiPrivateKeyFilepath pulumi.StringPtrInput
	// OCI Compartment OCID.
	OciCompartmentId pulumi.StringPtrInput
	// OCI Tenancy OCID.
	OciTenancyId pulumi.StringPtrInput
	// OCI User OCID.
	OciUserId pulumi.StringPtrInput
}

func (AccountState) ElementType() reflect.Type {
	return reflect.TypeOf((*accountState)(nil)).Elem()
}

type accountArgs struct {
	// Account name. This can be used for logging in to CloudN console or UserConnect controller.
	AccountName string `pulumi:"accountName"`
	// Alibaba Cloud Access Key.
	AlicloudAccessKey *string `pulumi:"alicloudAccessKey"`
	// Alibaba Cloud Account ID to associate with Aviatrix account.
	AlicloudAccountId *string `pulumi:"alicloudAccountId"`
	// Alibaba Cloud Secret Key.
	AlicloudSecretKey *string `pulumi:"alicloudSecretKey"`
	// Azure Application ID.
	ArmApplicationId *string `pulumi:"armApplicationId"`
	// Azure Application Key.
	ArmApplicationKey *string `pulumi:"armApplicationKey"`
	// Azure Directory ID.
	ArmDirectoryId *string `pulumi:"armDirectoryId"`
	// Azure Subscription ID.
	ArmSubscriptionId *string `pulumi:"armSubscriptionId"`
	// Enable account audit.
	AuditAccount *bool `pulumi:"auditAccount"`
	// AWS Access Key.
	AwsAccessKey *string `pulumi:"awsAccessKey"`
	// AWS Account number to associate with Aviatrix account. Should be 12 digits.
	AwsAccountNumber *string `pulumi:"awsAccountNumber"`
	// AWS App role ARN for gateways.
	AwsGatewayRoleApp *string `pulumi:"awsGatewayRoleApp"`
	// AWS EC2 role ARN for gateways.
	AwsGatewayRoleEc2 *string `pulumi:"awsGatewayRoleEc2"`
	// AWS IAM-role based flag.
	AwsIam *bool `pulumi:"awsIam"`
	// AWS App role ARN.
	AwsRoleApp *string `pulumi:"awsRoleApp"`
	// AWS EC2 role ARN.
	AwsRoleEc2 *string `pulumi:"awsRoleEc2"`
	// AWS Secret Key.
	AwsSecretKey *string `pulumi:"awsSecretKey"`
	// AWS China Access Key.
	AwschinaAccessKey *string `pulumi:"awschinaAccessKey"`
	// AWS China Account Number.
	AwschinaAccountNumber *string `pulumi:"awschinaAccountNumber"`
	// AWS China IAM-role based flag.
	AwschinaIam *bool `pulumi:"awschinaIam"`
	// AWS China App Role ARN.
	AwschinaRoleApp *string `pulumi:"awschinaRoleApp"`
	// AWS China EC2 Role ARN.
	AwschinaRoleEc2 *string `pulumi:"awschinaRoleEc2"`
	// AWS China Secret Key.
	AwschinaSecretKey *string `pulumi:"awschinaSecretKey"`
	// AWS Gov Access Key.
	AwsgovAccessKey *string `pulumi:"awsgovAccessKey"`
	// AWS Gov Account number to associate with Aviatrix account.
	AwsgovAccountNumber *string `pulumi:"awsgovAccountNumber"`
	// AWSGov IAM-role based flag
	AwsgovIam *bool `pulumi:"awsgovIam"`
	// AWSGov App role ARN
	AwsgovRoleApp *string `pulumi:"awsgovRoleApp"`
	// AWSGov EC2 role ARN
	AwsgovRoleEc2 *string `pulumi:"awsgovRoleEc2"`
	// AWS Gov Secret Key.
	AwsgovSecretKey *string `pulumi:"awsgovSecretKey"`
	// AWS Secret Region Account Number.
	AwssAccountNumber *string `pulumi:"awssAccountNumber"`
	// AWS Secret Region Custom Certificate Authority file path.
	AwssCaChainCert *string `pulumi:"awssCaChainCert"`
	// AWS Secret Region CAP Account Name.
	AwssCapAccountName *string `pulumi:"awssCapAccountName"`
	// AWS Secret Region CAP Agency.
	AwssCapAgency *string `pulumi:"awssCapAgency"`
	// AWS Secret Region CAP Certificate file path.
	AwssCapCert *string `pulumi:"awssCapCert"`
	// AWS Secret Region CAP Certificate Key file path.
	AwssCapCertKey *string `pulumi:"awssCapCertKey"`
	// AWS Secret Region CAP Role Name.
	AwssCapRoleName *string `pulumi:"awssCapRoleName"`
	// AWS Secret Region CAP Endpoint URL.
	AwssCapUrl *string `pulumi:"awssCapUrl"`
	// AWS Top Secret Region Account Number.
	AwstsAccountNumber *string `pulumi:"awstsAccountNumber"`
	// AWS Top Secret Region Custom Certificate Authority file path.
	AwstsCaChainCert *string `pulumi:"awstsCaChainCert"`
	// AWS Top Secret Region CAP Agency.
	AwstsCapAgency *string `pulumi:"awstsCapAgency"`
	// AWS Top Secret Region CAP Certificate file path.
	AwstsCapCert *string `pulumi:"awstsCapCert"`
	// AWS Top Secret Region CAP Certificate Key file path.
	AwstsCapCertKey *string `pulumi:"awstsCapCertKey"`
	// AWS Top Secret Region CAP Mission.
	AwstsCapMission *string `pulumi:"awstsCapMission"`
	// AWS Top Secret Region CAP Role Name.
	AwstsCapRoleName *string `pulumi:"awstsCapRoleName"`
	// AWS Top Secret Region CAP Endpoint URL.
	AwstsCapUrl *string `pulumi:"awstsCapUrl"`
	// Azure China Application ID.
	AzurechinaApplicationId *string `pulumi:"azurechinaApplicationId"`
	// Azure China Application Key.
	AzurechinaApplicationKey *string `pulumi:"azurechinaApplicationKey"`
	// Azure China Directory ID.
	AzurechinaDirectoryId *string `pulumi:"azurechinaDirectoryId"`
	// Azure China Subscription ID.
	AzurechinaSubscriptionId *string `pulumi:"azurechinaSubscriptionId"`
	// Azure Gov Application ID.
	AzuregovApplicationId *string `pulumi:"azuregovApplicationId"`
	// Azure Gov Application Key.
	AzuregovApplicationKey *string `pulumi:"azuregovApplicationKey"`
	// Azure Gov Directory ID.
	AzuregovDirectoryId *string `pulumi:"azuregovDirectoryId"`
	// Azure Gov Subscription ID.
	AzuregovSubscriptionId *string `pulumi:"azuregovSubscriptionId"`
	// Type of cloud service provider.
	CloudType int `pulumi:"cloudType"`
	// GCloud Project credentials local file path.
	GcloudProjectCredentialsFilepath *string `pulumi:"gcloudProjectCredentialsFilepath"`
	// GCloud Project ID.
	GcloudProjectId *string `pulumi:"gcloudProjectId"`
	// OCI API Private Key local file path.
	OciApiPrivateKeyFilepath *string `pulumi:"ociApiPrivateKeyFilepath"`
	// OCI Compartment OCID.
	OciCompartmentId *string `pulumi:"ociCompartmentId"`
	// OCI Tenancy OCID.
	OciTenancyId *string `pulumi:"ociTenancyId"`
	// OCI User OCID.
	OciUserId *string `pulumi:"ociUserId"`
}

// The set of arguments for constructing a Account resource.
type AccountArgs struct {
	// Account name. This can be used for logging in to CloudN console or UserConnect controller.
	AccountName pulumi.StringInput
	// Alibaba Cloud Access Key.
	AlicloudAccessKey pulumi.StringPtrInput
	// Alibaba Cloud Account ID to associate with Aviatrix account.
	AlicloudAccountId pulumi.StringPtrInput
	// Alibaba Cloud Secret Key.
	AlicloudSecretKey pulumi.StringPtrInput
	// Azure Application ID.
	ArmApplicationId pulumi.StringPtrInput
	// Azure Application Key.
	ArmApplicationKey pulumi.StringPtrInput
	// Azure Directory ID.
	ArmDirectoryId pulumi.StringPtrInput
	// Azure Subscription ID.
	ArmSubscriptionId pulumi.StringPtrInput
	// Enable account audit.
	AuditAccount pulumi.BoolPtrInput
	// AWS Access Key.
	AwsAccessKey pulumi.StringPtrInput
	// AWS Account number to associate with Aviatrix account. Should be 12 digits.
	AwsAccountNumber pulumi.StringPtrInput
	// AWS App role ARN for gateways.
	AwsGatewayRoleApp pulumi.StringPtrInput
	// AWS EC2 role ARN for gateways.
	AwsGatewayRoleEc2 pulumi.StringPtrInput
	// AWS IAM-role based flag.
	AwsIam pulumi.BoolPtrInput
	// AWS App role ARN.
	AwsRoleApp pulumi.StringPtrInput
	// AWS EC2 role ARN.
	AwsRoleEc2 pulumi.StringPtrInput
	// AWS Secret Key.
	AwsSecretKey pulumi.StringPtrInput
	// AWS China Access Key.
	AwschinaAccessKey pulumi.StringPtrInput
	// AWS China Account Number.
	AwschinaAccountNumber pulumi.StringPtrInput
	// AWS China IAM-role based flag.
	AwschinaIam pulumi.BoolPtrInput
	// AWS China App Role ARN.
	AwschinaRoleApp pulumi.StringPtrInput
	// AWS China EC2 Role ARN.
	AwschinaRoleEc2 pulumi.StringPtrInput
	// AWS China Secret Key.
	AwschinaSecretKey pulumi.StringPtrInput
	// AWS Gov Access Key.
	AwsgovAccessKey pulumi.StringPtrInput
	// AWS Gov Account number to associate with Aviatrix account.
	AwsgovAccountNumber pulumi.StringPtrInput
	// AWSGov IAM-role based flag
	AwsgovIam pulumi.BoolPtrInput
	// AWSGov App role ARN
	AwsgovRoleApp pulumi.StringPtrInput
	// AWSGov EC2 role ARN
	AwsgovRoleEc2 pulumi.StringPtrInput
	// AWS Gov Secret Key.
	AwsgovSecretKey pulumi.StringPtrInput
	// AWS Secret Region Account Number.
	AwssAccountNumber pulumi.StringPtrInput
	// AWS Secret Region Custom Certificate Authority file path.
	AwssCaChainCert pulumi.StringPtrInput
	// AWS Secret Region CAP Account Name.
	AwssCapAccountName pulumi.StringPtrInput
	// AWS Secret Region CAP Agency.
	AwssCapAgency pulumi.StringPtrInput
	// AWS Secret Region CAP Certificate file path.
	AwssCapCert pulumi.StringPtrInput
	// AWS Secret Region CAP Certificate Key file path.
	AwssCapCertKey pulumi.StringPtrInput
	// AWS Secret Region CAP Role Name.
	AwssCapRoleName pulumi.StringPtrInput
	// AWS Secret Region CAP Endpoint URL.
	AwssCapUrl pulumi.StringPtrInput
	// AWS Top Secret Region Account Number.
	AwstsAccountNumber pulumi.StringPtrInput
	// AWS Top Secret Region Custom Certificate Authority file path.
	AwstsCaChainCert pulumi.StringPtrInput
	// AWS Top Secret Region CAP Agency.
	AwstsCapAgency pulumi.StringPtrInput
	// AWS Top Secret Region CAP Certificate file path.
	AwstsCapCert pulumi.StringPtrInput
	// AWS Top Secret Region CAP Certificate Key file path.
	AwstsCapCertKey pulumi.StringPtrInput
	// AWS Top Secret Region CAP Mission.
	AwstsCapMission pulumi.StringPtrInput
	// AWS Top Secret Region CAP Role Name.
	AwstsCapRoleName pulumi.StringPtrInput
	// AWS Top Secret Region CAP Endpoint URL.
	AwstsCapUrl pulumi.StringPtrInput
	// Azure China Application ID.
	AzurechinaApplicationId pulumi.StringPtrInput
	// Azure China Application Key.
	AzurechinaApplicationKey pulumi.StringPtrInput
	// Azure China Directory ID.
	AzurechinaDirectoryId pulumi.StringPtrInput
	// Azure China Subscription ID.
	AzurechinaSubscriptionId pulumi.StringPtrInput
	// Azure Gov Application ID.
	AzuregovApplicationId pulumi.StringPtrInput
	// Azure Gov Application Key.
	AzuregovApplicationKey pulumi.StringPtrInput
	// Azure Gov Directory ID.
	AzuregovDirectoryId pulumi.StringPtrInput
	// Azure Gov Subscription ID.
	AzuregovSubscriptionId pulumi.StringPtrInput
	// Type of cloud service provider.
	CloudType pulumi.IntInput
	// GCloud Project credentials local file path.
	GcloudProjectCredentialsFilepath pulumi.StringPtrInput
	// GCloud Project ID.
	GcloudProjectId pulumi.StringPtrInput
	// OCI API Private Key local file path.
	OciApiPrivateKeyFilepath pulumi.StringPtrInput
	// OCI Compartment OCID.
	OciCompartmentId pulumi.StringPtrInput
	// OCI Tenancy OCID.
	OciTenancyId pulumi.StringPtrInput
	// OCI User OCID.
	OciUserId pulumi.StringPtrInput
}

func (AccountArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*accountArgs)(nil)).Elem()
}

type AccountInput interface {
	pulumi.Input

	ToAccountOutput() AccountOutput
	ToAccountOutputWithContext(ctx context.Context) AccountOutput
}

func (*Account) ElementType() reflect.Type {
	return reflect.TypeOf((**Account)(nil)).Elem()
}

func (i *Account) ToAccountOutput() AccountOutput {
	return i.ToAccountOutputWithContext(context.Background())
}

func (i *Account) ToAccountOutputWithContext(ctx context.Context) AccountOutput {
	return pulumi.ToOutputWithContext(ctx, i).(AccountOutput)
}

// AccountArrayInput is an input type that accepts AccountArray and AccountArrayOutput values.
// You can construct a concrete instance of `AccountArrayInput` via:
//
//          AccountArray{ AccountArgs{...} }
type AccountArrayInput interface {
	pulumi.Input

	ToAccountArrayOutput() AccountArrayOutput
	ToAccountArrayOutputWithContext(context.Context) AccountArrayOutput
}

type AccountArray []AccountInput

func (AccountArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*Account)(nil)).Elem()
}

func (i AccountArray) ToAccountArrayOutput() AccountArrayOutput {
	return i.ToAccountArrayOutputWithContext(context.Background())
}

func (i AccountArray) ToAccountArrayOutputWithContext(ctx context.Context) AccountArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(AccountArrayOutput)
}

// AccountMapInput is an input type that accepts AccountMap and AccountMapOutput values.
// You can construct a concrete instance of `AccountMapInput` via:
//
//          AccountMap{ "key": AccountArgs{...} }
type AccountMapInput interface {
	pulumi.Input

	ToAccountMapOutput() AccountMapOutput
	ToAccountMapOutputWithContext(context.Context) AccountMapOutput
}

type AccountMap map[string]AccountInput

func (AccountMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*Account)(nil)).Elem()
}

func (i AccountMap) ToAccountMapOutput() AccountMapOutput {
	return i.ToAccountMapOutputWithContext(context.Background())
}

func (i AccountMap) ToAccountMapOutputWithContext(ctx context.Context) AccountMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(AccountMapOutput)
}

type AccountOutput struct{ *pulumi.OutputState }

func (AccountOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Account)(nil)).Elem()
}

func (o AccountOutput) ToAccountOutput() AccountOutput {
	return o
}

func (o AccountOutput) ToAccountOutputWithContext(ctx context.Context) AccountOutput {
	return o
}

type AccountArrayOutput struct{ *pulumi.OutputState }

func (AccountArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*Account)(nil)).Elem()
}

func (o AccountArrayOutput) ToAccountArrayOutput() AccountArrayOutput {
	return o
}

func (o AccountArrayOutput) ToAccountArrayOutputWithContext(ctx context.Context) AccountArrayOutput {
	return o
}

func (o AccountArrayOutput) Index(i pulumi.IntInput) AccountOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *Account {
		return vs[0].([]*Account)[vs[1].(int)]
	}).(AccountOutput)
}

type AccountMapOutput struct{ *pulumi.OutputState }

func (AccountMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*Account)(nil)).Elem()
}

func (o AccountMapOutput) ToAccountMapOutput() AccountMapOutput {
	return o
}

func (o AccountMapOutput) ToAccountMapOutputWithContext(ctx context.Context) AccountMapOutput {
	return o
}

func (o AccountMapOutput) MapIndex(k pulumi.StringInput) AccountOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *Account {
		return vs[0].(map[string]*Account)[vs[1].(string)]
	}).(AccountOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*AccountInput)(nil)).Elem(), &Account{})
	pulumi.RegisterInputType(reflect.TypeOf((*AccountArrayInput)(nil)).Elem(), AccountArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*AccountMapInput)(nil)).Elem(), AccountMap{})
	pulumi.RegisterOutputType(AccountOutput{})
	pulumi.RegisterOutputType(AccountArrayOutput{})
	pulumi.RegisterOutputType(AccountMapOutput{})
}
