// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package config

import (
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi/config"
)

func GetControllerIp(ctx *pulumi.Context) string {
	return config.Get(ctx, "avxmlin:controllerIp")
}
func GetPassword(ctx *pulumi.Context) string {
	return config.Get(ctx, "avxmlin:password")
}
func GetPathToCaCertificate(ctx *pulumi.Context) string {
	return config.Get(ctx, "avxmlin:pathToCaCertificate")
}
func GetSkipVersionValidation(ctx *pulumi.Context) bool {
	return config.GetBool(ctx, "avxmlin:skipVersionValidation")
}
func GetUsername(ctx *pulumi.Context) string {
	return config.Get(ctx, "avxmlin:username")
}
func GetVerifySslCertificate(ctx *pulumi.Context) bool {
	return config.GetBool(ctx, "avxmlin:verifySslCertificate")
}
