// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

declare var exports: any;
const __config = new pulumi.Config("aviatrix");

export declare const controllerIp: string | undefined;
Object.defineProperty(exports, "controllerIp", {
    get() {
        return __config.get("controllerIp");
    },
    enumerable: true,
});

export declare const password: string | undefined;
Object.defineProperty(exports, "password", {
    get() {
        return __config.get("password");
    },
    enumerable: true,
});

export declare const pathToCaCertificate: string | undefined;
Object.defineProperty(exports, "pathToCaCertificate", {
    get() {
        return __config.get("pathToCaCertificate");
    },
    enumerable: true,
});

export declare const skipVersionValidation: boolean;
Object.defineProperty(exports, "skipVersionValidation", {
    get() {
        return __config.getObject<boolean>("skipVersionValidation") ?? true;
    },
    enumerable: true,
});

export declare const username: string | undefined;
Object.defineProperty(exports, "username", {
    get() {
        return __config.get("username");
    },
    enumerable: true,
});

export declare const verifySslCertificate: boolean | undefined;
Object.defineProperty(exports, "verifySslCertificate", {
    get() {
        return __config.getObject<boolean>("verifySslCertificate");
    },
    enumerable: true,
});

