# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from . import _utilities
import typing
# Export this package's modules as members:
from .account import *
from .gateway import *
from .provider import *
from .spoke_gateway import *
from .transit_gateway import *
from .vpc import *
from ._inputs import *
from . import outputs

# Make subpackages available:
if typing.TYPE_CHECKING:
    import pulumi_aviatrix.config as __config
    config = __config
else:
    config = _utilities.lazy_import('pulumi_aviatrix.config')

_utilities.register(
    resource_modules="""
[
 {
  "pkg": "aviatrix",
  "mod": "index/account",
  "fqn": "pulumi_aviatrix",
  "classes": {
   "aviatrix:index/account:Account": "Account"
  }
 },
 {
  "pkg": "aviatrix",
  "mod": "index/gateway",
  "fqn": "pulumi_aviatrix",
  "classes": {
   "aviatrix:index/gateway:Gateway": "Gateway"
  }
 },
 {
  "pkg": "aviatrix",
  "mod": "index/spokeGateway",
  "fqn": "pulumi_aviatrix",
  "classes": {
   "aviatrix:index/spokeGateway:SpokeGateway": "SpokeGateway"
  }
 },
 {
  "pkg": "aviatrix",
  "mod": "index/transitGateway",
  "fqn": "pulumi_aviatrix",
  "classes": {
   "aviatrix:index/transitGateway:TransitGateway": "TransitGateway"
  }
 },
 {
  "pkg": "aviatrix",
  "mod": "index/vpc",
  "fqn": "pulumi_aviatrix",
  "classes": {
   "aviatrix:index/vpc:Vpc": "Vpc"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "aviatrix",
  "token": "pulumi:providers:aviatrix",
  "fqn": "pulumi_aviatrix",
  "class": "Provider"
 }
]
"""
)
