// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package aviatrix

import (
	"fmt"

	"github.com/blang/semver"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type module struct {
	version semver.Version
}

func (m *module) Version() semver.Version {
	return m.version
}

func (m *module) Construct(ctx *pulumi.Context, name, typ, urn string) (r pulumi.Resource, err error) {
	switch typ {
	case "aviatrix:index/account:Account":
		r = &Account{}
	case "aviatrix:index/gateway:Gateway":
		r = &Gateway{}
	case "aviatrix:index/gatewaySNAT:GatewaySNAT":
		r = &GatewaySNAT{}
	case "aviatrix:index/spokeGateway:SpokeGateway":
		r = &SpokeGateway{}
	case "aviatrix:index/transitGateway:TransitGateway":
		r = &TransitGateway{}
	case "aviatrix:index/vpc:Vpc":
		r = &Vpc{}
	default:
		return nil, fmt.Errorf("unknown resource type: %s", typ)
	}

	err = ctx.RegisterResource(typ, name, nil, r, pulumi.URN_(urn))
	return
}

type pkg struct {
	version semver.Version
}

func (p *pkg) Version() semver.Version {
	return p.version
}

func (p *pkg) ConstructProvider(ctx *pulumi.Context, name, typ, urn string) (pulumi.ProviderResource, error) {
	if typ != "pulumi:providers:aviatrix" {
		return nil, fmt.Errorf("unknown provider type: %s", typ)
	}

	r := &Provider{}
	err := ctx.RegisterResource(typ, name, nil, r, pulumi.URN_(urn))
	return r, err
}

func init() {
	version, _ := PkgVersion()
	pulumi.RegisterResourceModule(
		"aviatrix",
		"index/account",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"aviatrix",
		"index/gateway",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"aviatrix",
		"index/gatewaySNAT",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"aviatrix",
		"index/spokeGateway",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"aviatrix",
		"index/transitGateway",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"aviatrix",
		"index/vpc",
		&module{version},
	)
	pulumi.RegisterResourcePackage(
		"aviatrix",
		&pkg{version},
	)
}
