// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import { input as inputs, output as outputs } from "../types";

export interface VpcPrivateSubnet {
    cidr?: pulumi.Input<string>;
    name?: pulumi.Input<string>;
    subnetId?: pulumi.Input<string>;
}

export interface VpcPublicSubnet {
    cidr?: pulumi.Input<string>;
    name?: pulumi.Input<string>;
    subnetId?: pulumi.Input<string>;
}

export interface VpcSubnet {
    cidr?: pulumi.Input<string>;
    name?: pulumi.Input<string>;
    region?: pulumi.Input<string>;
    subnetId?: pulumi.Input<string>;
}
