// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import { input as inputs, output as outputs } from "../types";

export interface TransitGatewayBgpLanInterface {
    subnet: string;
    vpcId: string;
}

export interface TransitGatewayHaBgpLanInterface {
    subnet: string;
    vpcId: string;
}

export interface VpcPrivateSubnet {
    cidr: string;
    name: string;
    subnetId: string;
}

export interface VpcPublicSubnet {
    cidr: string;
    name: string;
    subnetId: string;
}

export interface VpcSubnet {
    cidr?: string;
    name?: string;
    region?: string;
    subnetId: string;
}

